config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  get 'course_schedules', to: 'course_schedules#index', as: :course_schedules
  get 'information/parents', to: 'information#parents', as: :parents
  get 'information/syllabus', to: 'information#syllabus', as: :syllabus
  get 'information/outline', to: 'information#outline', as: :outline
  get 'about/michael_morgan', to: 'about#michael_morgan', as: :michael_morgan
  get 'about/larry_quimby', to: 'about#larry_quimby', as: :larry_quimby
  get 'about/ly_hua', to: 'about#ly_hua', as: :ly_hua
  get 'about/chem_club', to: 'about#chem_club', as: :chem_club
  get 'handouts/AP', to: 'handouts#ap', as: :ap
  get 'handouts/non_AP', to: 'handouts#non_ap', as: :non_ap
  get 'handouts/practice', to: 'handouts#practice', as: :practice

  root 'welcome#index'
  resources :announcements, :schedules, :information

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
	validates :title, presence: true
	validates :content, presence: true
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	validates :title, presence: true
	validates :content, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
	layout "admin"
	http_basic_authenticate_with name: "mmorgan", password: "crazyKat"

	def index
		@announcements = Announcement.all.order('date DESC')
	end

	def new
		@announcement = Announcement.new
	end

	def show
		@announcement = Announcement.find(params[:id])
	end

	def edit
		@announcement = Announcement.find(params[:id])
	end

	def update
		@announcement = Announcement.find(params[:id])

		if @announcement.update(announcement_params)
			redirect_to @announcement
		else
			render 'edit'
		end
	end

	def create
		@announcement = Announcement.new(announcement_params)

		if @announcement.save
			redirect_to @announcement
		else
			render 'new'
		end
	end

	def destroy
		@announcement = Announcement.find(params[:id])
		@announcement.destroy

		redirect_to announcements_path
	end

	private
		def announcement_params
			params.require(:announcement).permit(:title, :date, :category, :content)
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/course_schedules_controller.rb
class CourseSchedulesController < ApplicationController
	def index
		@schedules = Schedule.all.order('date DESC')
	end
end

app/controllers/handouts_controller.rb
class HandoutsController < ApplicationController
	def ap
	end
	def practice
	end
	def non_ap
	end
end

app/controllers/information_controller.rb
class InformationController < ApplicationController
	def parents
	end
	def syllabus
	end
	def state_standards
	end
	def contract
	end
	def outline
	end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	layout "admin"
	http_basic_authenticate_with name: "mmorgan", password: "crazyKat"

	def index
		@schedules = Schedule.all.order('date DESC')
	end
	def new
		@schedule = Schedule.new
	end

	def show
		@schedule = Schedule.find(params[:id])
	end

	def edit
		@schedule = Schedule.find(params[:id])
	end

	def update
		@schedule = Schedule.find(params[:id])

		if @schedule.update(schedule_params)
			redirect_to @schedule
		else
			render 'edit'
		end
	end

	def create
		@schedule = Schedule.new(schedule_params)

		if @schedule.save
			redirect_to @schedule
		else
			render 'new'
		end
	end

	def destroy
		@schedule = Schedule.find(params[:id])
		@schedule.destroy

		redirect_to schedules_path
	end

	private
		def schedule_params
			params.require(:schedule).permit(:title, :date, :category, :content)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@announcements = Announcement.all.order('date DESC')
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_schedules_helper.rb
module CourseSchedulesHelper
end

app/helpers/handouts_helper.rb
module HandoutsHelper
end

app/helpers/information_helper.rb
module InformationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/chem_club.html.erb
<section class="container">
	<div class="col-md-8 col-md-offset-2 article">
		<h2>Chemistry Club</h2>
		<p>Sorry this page is currently under development. Please try again later</p>
</section>
<!-- jQuery -->
<script src="//code.jquery.com/jquery.js"></script>
<!-- Bootstrap JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/about/larry_quimby.html.erb
<section class="container">
	<div class="col-md-8 col-md-offset-2 article">
		<h1>Larry Quimby</h1>
		<br>
		<p><%= image_tag('quimby_profile.jpg', width: '130px', class: 'profile', align: 'left') %>Mr. Quimby currently teaches Physics and Chemistry at Francisco Bravo Medical Magnet High School. He is active with the group of teachers that run the annual Physics Students Day at Magic Mountain. He is also a member of The American Association of Physics Teachers and an active participant at the annual meeting for physics teachers that is held at Occidental College.
		<p>He has degrees in Physics from the California State University at Los Angeles and Astronomy from the University of California at Los Angeles. While doing the coursework leading to his teaching credential at CSULA he studied under and was greatly influenced Dr. Edwin Hirsch whose goal was to never give a lecture without at least one demonstration. Mr. Quimby participated in the Minority High School Student Research Apprentice Program sponsored by the National Institutes of Health.</p>
		<p>Prior to coming to Bravo, he taught Physics, Chemistry, Physical Science, and a few other classes at South Gate High School. He also worked part time as an instructor at CSU Dominguez Hills teaching introductory computer usage and programming classes. He is also involved heavily with the Chemistry Outreach program here at Bravo.</p>
		<p><b>Email: lquimby@lausd.net</b></p>
	</div>
</section>
<!-- jQuery -->
<script src="//code.jquery.com/jquery.js"></script>
<!-- Bootstrap JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/about/ly_hua.html.erb
<section class="container">
	<div class="col-md-8 col-md-offset-2 article">
		<h1>Ly S. Hua</h1>
		<br>
		<p><%= image_tag('hua_profile.JPG', width: '130px', class: 'profile', align: 'left') %>Ly Hua was born in Vietnam and immigrated to Augusta, Maine when he was only a year old. He spent his early childhood (until age 7) in Augusta, then moved to Los Angeles in 1986. </p>

		<p>Mr. Hua grew up in East Los Angeles and attended Bravo Medical Magnet from 10th to 12th grade. He graduated in 1997 after experiencing many of the opportunities Bravo had to offer. Such activities included the Academic Decathlon, Varsity Track and Field, Junior Statesmen of America, and Varsity Basketball. He was also the Valedictorian speaker for his graduating class. </p>
		<p>After Bravo, Mr. Hua attended the University of California, San Diego. He graduated in 2001 with a Biochemistry/Molecular Biology Degree. </p>
		<p>In 2003, Mr. Hua was invited to return to Bravo as a science teacher. The chance to work alongside his past coaches, teachers, and mentors was an opportunity he could not refuse. Since then, Mr. Hua has taught Integrated Science, Biology, Physiology, and Chemistry. Mr. Hua would also like to start a Biochemistry/Molecular Biology electives course for students with a passion for science. Since his return, Mr. Hua has also helped coach J.V. Boys Basketball, Track and Field, and was part of the trio of coaches that helped put Bravo's Swim Team on the map in its first year.</p>
		<p>Away from school, Mr. Hua enjoys basketball, weight-training, and swimming.</p>
		<p><b>Email Mr. Hua: lsh4010@epals.lausd.k12.ca.us </b></p>
	</div>
</section>
<!-- jQuery -->
<script src="//code.jquery.com/jquery.js"></script>
<!-- Bootstrap JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/announcements/_form.html.erb
<%= form_for(@announcement) do |f| %>
  <% if @announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
      <% @announcement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/announcements/edit.html.erb
	<body>
		<div class="container">
			<%= form_for :announcement, url: announcement_path(:id => @announcement.id), method: :patch do |f| %>
				<% if @announcement.errors.any? %>
				<div class="errors">
					<h2>The following <%= pluralize(@announcement.errors.count, "error") %> prohibited this
						announcement from being saved:</h2>
						<ul>
							<% @announcement.errors.full_messages.each do |message| %>
							<li><%= message %></li>
							<% end %>
						</ul>
				</div>
				<% end %>
				<p>
			    <%= f.label :title %>
			    <%= f.text_field :title %>
				</p>

				<p>
				<%= f.label :date %>
				<%= f.date_select :date %>
				</p>

				<p>
			  	<%= f.label :category %>
			  	<%= f.select :category, options_for_select(['AP Chemistry', 'Honors Chemistry', 'Regular Chemistry', 'Album of the Week']) %>
				</p>

			  	<p>
			    <%= f.label :content %><br>
			    <%= f.text_area :content, :class => 'ckeditor' %>
			  	</p>

			  	<p>
			    <%= f.submit %>
			  	</p>
			<% end %>
		</div>
		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/announcements/index.html.erb
<section class="container content home">
    <div class="row">
        <section class="scrollspy clearfix col col-md-3 hidden-sm hidden-xs">
            <ul class="affix nav nav-list" data-type="scrollspy">
                <li><a href="#june"><span class="glyphicon glyphicon-calendar"></span> June</a></li>
                <li><a href="#may"><span class="glyphicon glyphicon-calendar"></span> May</a></li>
                <li><a href="#april"><span class="glyphicon glyphicon-calendar"></span> April</a></li>
                <li><a href="#march"><span class="glyphicon glyphicon-calendar"></span> March</a></li>
                <li><a href="#february"><span class="glyphicon glyphicon-calendar"></span> February</a></li>
                <li><a href="#january"><span class="glyphicon glyphicon-calendar"></span> January</a></li>
                <li><a href="#december"><span class="glyphicon glyphicon-calendar"></span> December</a></li>
                <li><a href="#november"><span class="glyphicon glyphicon-calendar"></span> November</a></li>
                <li><a href="#october"><span class="glyphicon glyphicon-calendar"></span> October</a></li>
                <li><a href="#september"><span class="glyphicon glyphicon-calendar"></span> September</a></li>
                <li><a href="#august"><span class="glyphicon glyphicon-calendar"></span> August</a></li>
                <li><a href="#july"><span class="glyphicon glyphicon-calendar"></span> July</a></li>
            </ul>
            <div class="clearfix"></div>
        </section>
        <span class="col-md-9 announcements">
            <h1 class="category">All Announcements</h1>
            <div data-no-turbolink>
            <%= link_to new_announcement_path do %>
                <span class="glyphicon glyphicon-plus-sign"></span> New Announcement
            <% end %>
            <div class="btn-group sub-filter">
                <button type="button" class="btn btn-default all">All</button>
                <button type="button" class="btn btn-default ap">AP Chemistry</button>
                <button type="button" class="btn btn-default honors">Honors Chemistry</button>
                <button type="button" class="btn btn-default regular">Regular Chemistry</button>
                <button type="button" class="btn btn-default album">Album of the Week</button>
            </div>
            </div>

            <% @announcements.each do |announcement| %>
            <div class="post <%= announcement.category %>" id="<%= announcement.date.strftime("%B").downcase %>">
                <hr>
                <span class="icon">
                                <%= link_to announcement_path(announcement), method: :DELETE, data: {confirm: "Are you sure you want to delete this announcement? There is no going back!" } do %>
                                <span class="glyphicon glyphicon-remove"></span>Delete
                                <% end %>
                            </span>
                            <span class="icon" data-no-turbolink>
                                <%= link_to edit_announcement_path(announcement) do %>
                                <span class="glyphicon glyphicon-pencil"></span>Edit
                                <% end %>
                            </span>
                            <h2 class="title">
                            <%= announcement.date.strftime("%B %d, %Y") %>: <%= announcement.title %>
                            </h2>
                <%= raw announcement.content %>
            </div>
            <% end %>

        </span>
    </div>
</section>

<script>
    $(document).ready(function(){
        $(".sub-filter").on('click', "button",function(){
            var category = $(this).text();
            if (category == "All"){
                $(".post").removeClass("hidden");
                $(".category").text(category+" Announcements");
            } else if(category == "Album of the Week"){
                $(".post").addClass("hidden");
                $(".Album").removeClass("hidden");
                $(".category").text("Album of the Week");
            } else {
                $(".post").addClass("hidden");
                $("." + category.slice(0,-9)).removeClass("hidden");
                $(".category").text(category);
            }
        });
        var $window = $(window);

        $('section.scrollspy').each(function(){
            var $obj = $('.scrollspy .nav'); // assigning the object
            $(window).scroll(function() {
                if ($window.scrollTop() < 370 ) {
                    var yPos = 370-$window.scrollTop();
                }
                else{
                    var yPos = 20;
                }
                $obj.css({"top" : yPos + "px" });
            });
        });
    });
</script>

<!-- jQuery -->
<script src="//code.jquery.com/jquery.js"></script>
<!-- Bootstrap JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/announcements/show.html.erb
		<div class="container">
			<h2>
				<%= @announcement.title %>
			</h2>
			<h2>
				<%= @announcement.date %>
			</h2>
			<%= raw @announcement.content %>
			<div data-no-turbolink class='archive-button'>
				<%= link_to announcements_path do %>
				<button type="button" class="btn btn-default">Announcement Archive</button>
				<% end %>
			</div>
		</div>

		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Morgan Chemistry</title>
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:400,700|Medula+One' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <script src="/ckeditor/ckeditor.js"></script>
  <link href='/chemistry_favicon.ico' rel='shortcut icon' >
</head>
<body data-spy="scroll" data-target=".scrollspy">
<section class="container" id="header">
<div id="banner">
    <%= image_tag('Banner3.jpg', class: 'img-responsive') %>
</div>
<nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav nav-justified navbar-nav">
                <li><%= link_to "Home", announcements_path %></li>
                <li class="dropdown">
                    <%= link_to "Course Schedule", schedules_path %>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Course Information<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "For Parents", parents_path %></li>
                        <li><%= link_to "Outline", outline_path %></li>
                        <li><%= link_to "Syllabus", syllabus_path %></li>
                        <li><a href="#">Contract</a></li>
                        <li><a href="http://www.cde.ca.gov/be/st/ss/documents/sciencestnd.pdf">State Standards</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Course Handouts<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Non-AP Chemistry", non_ap_path %></li>
                        <li><%= link_to "AP Chemistry", ap_path %></li>
                        <li><%= link_to "Practice Tests", practice_path %></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Michael Morgan", michael_morgan_path %></li>
                        <li><%= link_to "Larry Quimby", larry_quimby_path %></li>
                        <li><%= link_to "Ly Hua", ly_hua_path %></li>
                        <li><%= link_to "Chem Club", chem_club_path %></li>
                        <li><a href="http://www.morganchem.com/physics/Physics_Home.html">Physics Page</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- close navbar-collapse -->
</nav>
</section>
<%= yield %>
 <script>
    // Replace the <textarea id="editor1"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace( '.ckeditor' );
</script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Morgan Chemistry</title>
  <link href='http://fonts.googleapis.com/css?family=Alegreya+Sans+SC:400,700|Medula+One' rel='stylesheet' type='text/css'>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  <%= csrf_meta_tags %>
  <link href='/chemistry_favicon.ico' rel='shortcut icon' >
</head>
<body data-spy="scroll" data-target=".scrollspy">
<section class="container" id="header">
<div id="banner">
    <%= image_tag('Banner3.jpg', class: 'img-responsive') %>
</div>
<nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav nav-justified navbar-nav">
                <li><%= link_to "Home", root_path %></li>
                <li class="dropdown">
                    <%= link_to "Course Schedule", course_schedules_path %>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Course Information<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "For Parents", parents_path %></li>
                        <li><%= link_to "Outline", outline_path %></li>
                        <li><%= link_to "Syllabus", syllabus_path %></li>
                        <li><a href="#">Contract</a></li>
                        <li><a href="http://www.cde.ca.gov/be/st/ss/documents/sciencestnd.pdf">State Standards</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Course Handouts<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Non-AP Chemistry", non_ap_path %></li>
                        <li><%= link_to "AP Chemistry", ap_path %></li>
                        <li><%= link_to "Practice Tests", practice_path %></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">About<span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Michael Morgan", michael_morgan_path %></li>
                        <li><%= link_to "Larry Quimby", larry_quimby_path %></li>
                        <li><%= link_to "Ly Hua", ly_hua_path %></li>
                        <li><%= link_to "Chem Club", chem_club_path %></li>
                        <li><a href="http://www.morganchem.com/physics/Physics_Home.html">Physics Page</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- close navbar-collapse -->
</nav>
</section>
<%= yield %>
</body>
</html>

app/views/schedules/edit.html.erb
	<body>
		<div class="container">
			<%= form_for :schedule, url: schedule_path(:id => @schedule.id), method: :patch do |f| %>
				<% if @schedule.errors.any? %>
				<div class="errors">
					<h2>The following <%= pluralize(@schedule.errors.count, "error") %> prohibited this
						schedule from being saved:</h2>
						<ul>
							<% @schedule.errors.full_messages.each do |message| %>
							<li><%= message %></li>
							<% end %>
						</ul>
				</div>
				<% end %>
				<p>
			    <%= f.label :title %>
			    <%= f.text_field :title %>
				</p>

				<p>
				<%= f.label :date %>
				<%= f.date_select :date %>
				</p>

				<p>
			  	<%= f.label :category %>
			  	<%= f.select :category, options_for_select(['Honors Chemistry', 'Regular Chemistry']) %>
				</p>

			  	<p>
			    <%= f.label :content %><br>
			    <%= f.text_area :content, :class => 'ckeditor' %>
			  	</p>

			  	<p>
			    <%= f.submit %>
			  	</p>
			<% end %>
		</div>
		<!-- jQuery -->
		<script src="//code.jquery.com/jquery.js"></script>
		<!-- Bootstrap JavaScript -->
		<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

app/views/schedules/index.html.erb
<section class="container content">
    <div class="row">
        <section class="scrollspy clearfix col col-md-3 hidden-sm hidden-xs">
            <ul class="affix nav nav-list" data-type="scrollspy">
                <li><a href="#june"><span class="glyphicon glyphicon-calendar"></span> June</a></li>
                <li><a href="#may"><span class="glyphicon glyphicon-calendar"></span> May</a></li>
                <li><a href="#april"><span class="glyphicon glyphicon-calendar"></span> April</a></li>
                <li><a href="#march"><span class="glyphicon glyphicon-calendar"></span> March</a></li>
                <li><a href="#february"><span class="glyphicon glyphicon-calendar"></span> February</a></li>
                <li><a href="#january"><span class="glyphicon glyphicon-calendar"></span> January</a></li>
                <li><a href="#december"><span class="glyphicon glyphicon-calendar"></span> December</a></li>
                <li><a href="#november"><span class="glyphicon glyphicon-calendar"></span> November</a></li>
                <li><a href="#october"><span class="glyphicon glyphicon-calendar"></span> October</a></li>
                <li><a href="#september"><span class="glyphicon glyphicon-calendar"></span> September</a></li>
                <li><a href="#august"><span class="glyphicon glyphicon-calendar"></span> August</a></li>
                <li><a href="#july"><span class="glyphicon glyphicon-calendar"></span> July</a></li>
            </ul>
            <div class="clearfix"></div>
        </section>
        <span class="col-md-9 schedules">
            <h1 class="category">All Schedules</h1>
            <div data-no-turbolink>
            <%= link_to new_schedule_path do %>
                <span class="glyphicon glyphicon-plus-sign"></span> New Schedule
            <% end %>
            <div class="btn-group sub-filter">
                <button type="button" class="btn btn-default all" value="Regular">All</button>
                <button type="button" class="btn btn-default honors">Honors Chemistry</button>
                <button type="button" class="btn btn-default regular">Regular Chemistry</button>
            </div>
            </div>

            <% @schedules.each do |schedule| %>
            <div class="post <%= schedule.category %>" id="<%= schedule.date.strftime("%B").downcase %>">
                <hr>
                <span class="icon">
                                <%= link_to schedule_path(schedule), method: :DELETE, data: {confirm: "Are you sure you want to delete this schedule? There is no going back!" } do %>
                                <span class="glyphicon glyphicon-remove"></span>Delete
                                <% end %>
                            </span>
                            <span class="icon" data-no-turbolink>
                                <%= link_to edit_schedule_path(schedule) do %>
                                <span class="glyphicon glyphicon-pencil"></span>Edit
                                <% end %>
                            </span>
                            <h2 class="title">
                            <%= schedule.date.strftime("%B %d, %Y") %>: <%= schedule.title %>
                            </h2>
                <%= raw schedule.content %>
            </div>
            <% end %>

        </span>
    </div>
</section>
<script>
    $(document).ready(function(){
        $(".sub-filter").on('click', "button",function(){
            var category = $(this).text();
            if (category == "All"){
                $(".post").removeClass("hidden");
                $(".category").text(category+" Schedules");
            } else {
                $(".post").addClass("hidden");
                $("." + category.slice(0,-9)).removeClass("hidden");
                $(".category").text(category);
            }
        });
        var $window = $(window);

        $('section.scrollspy').each(function(){
            var $obj = $('.scrollspy .nav'); // assigning the object
            $(window).scroll(function() {
                if ($window.scrollTop() < 370 ) {
                    var yPos = 370-$window.scrollTop();
                }
                else{
                    var yPos = 20;
                }
                $obj.css({"top" : yPos + "px" });
            });
        });
    });
</script>

<!-- jQuery -->
<script src="//code.jquery.com/jquery.js"></script>
<!-- Bootstrap JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>